name: neurometry
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - scikit-image>=0.19.2
  - pandas
  - pip:
    - black
    - flake8
    - flake8-docstrings
    - giotto-ph
    - git+https://github.com/geomstats/geomstats.git
    - hyperopt==0.2.5
    - isort
    - jupyter
    - jupyterlab-code-formatter
    - mat73
    - pre-commit
    - pytest
    - ray
    - ray[tune]
    - torch
    - wandb
    - seaborn
    - plotly
    # pyLDDMM dependencies:
    # - cycler==0.10.0
    # - decorator==4.4.1
    # - imageio==2.6.1
    # - kiwisolver==1.1.0
    # - matplotlib==3.1.2
    # - networkx==2.4
    # - Pillow==6.2.1
    # - pyparsing==2.4.6
    # - python-dateutil==2.8.1
    # - PyWavelets==1.1.1
    # - scikit-image==0.16.2
    # - scipy==1.4.1
    # - six==1.13.0
    # - numpy==1.24.3

