name: neuralgeom
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - scikit-image>=0.19.2
  - pandas
  - pip:
    - black
    - flake8
    - flake8-docstrings
    - giotto-ph
    - git+https://github.com/geomstats/geomstats.git
    - hyperopt==0.2.5
    - isort
    - jupyter
    - jupyterlab-code-formatter
    - mat73
    - pre-commit
    - pytest
    - ray
    - ray[tune]
    - torch
    - wandb
