name: abn
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.3.4
  - numpy>=1.18.1
  - pandas
  - pip
  - python=3.9
  - scikit-image>=0.19.2
  - scipy>=1.4.1
  - pip:
    - black
    - flake8
    - flake8-docstrings
    - git+https://github.com/geomstats/geomstats.git
    - isort
    - jupyter
    - mat73
    - pre-commit
    - pre-commit
    - torch>=1.1.9
